# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

#VARS
variables:
  buildConfiguration: 'Release'
  pathtosolution: 'Woodruff_Nathan_Project1/'
  pathtoproject: 'Woodruff_Nathan_Project1/WebApplication/'

#STEPS
steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarConnection'
    organization: 'nwoodr94-github'
    scannerMode: 'MSBuild'
    projectKey: 'nwoodr94_CSharp'
    projectName: 'Web Application'


#BUILD
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet build $(buildConfiguration)'


#ANALYZE
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: SonarCloudAnalyze@1

#PUBLISH
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1